// Centralized content + i18n
const COPY = {
  es: {
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      products: 'Productos',
      about: 'Nosotros',
      cases: 'Casos',
      quote: 'Cotizar',
    },
    hero: {
      eyebrow: 'Comercio exterior · Importación y exportación',
      kicker: 'Operadores de comercio exterior',
      lineA: 'De la huerta',
      lineB: 'al puerto',
      lineC: 'al mundo.',
      titleEm: 'al mundo',
      lede: 'Movemos contenedores de fruta, verdura y carga general a 16 países con red propia en aduanas, almacenes refrigerados y agentes marítimos. Una sola firma, una sola responsabilidad.',
      ctaPrimary: 'Solicitar cotización',
      ctaSecondary: 'Ver operación en vivo',
      stats: [
        { n: '16+', l: 'Países activos' },
        { n: '20', l: 'Años de operación' },
        { n: '99.4%', l: 'Cumplimiento de tiempos' },
      ],
      live: [
        { code: 'MZT → ROT', cargo: 'Aguacate Hass', status: 'EN MAR' },
        { code: 'GDL → DXB', cargo: 'Limón Persa', status: 'ADUANA' },
        { code: 'LIM → BCN', cargo: 'Espárrago', status: 'CARGADO' },
      ],
    },
    parallax: {
      lineA: 'En este momento,',
      lineB: 'movemos esto.',
    },
    ticker: ['MARÍTIMO', 'AÉREO', 'TERRESTRE', 'ADUANAS', 'ALMACENAJE', 'CONSOLIDACIÓN', 'SEGUROS DE CARGA', 'TRAZABILIDAD 24/7', 'CONTENEDOR COMPLETO', 'GRUPAJE'],
    services: {
      num: '01',
      title: ['Servicios de', 'logística global.'],
      titleEm: 'logística global',
      lede: 'Acompañamos cada operación de origen a destino. Una sola interlocución para todo tu flujo de exportación e importación.',
      items: [
        { name: 'Importación', desc: 'Gestión integral de importaciones por contenedor con asesoría arancelaria, despacho aduanal y entrega final.' },
        { name: 'Exportación', desc: 'Coordinamos la exportación de fruta, verdura y carga general hacia los principales mercados de Europa, América y Asia.' },
        { name: 'Logística & Aduanas', desc: 'Red de agentes aduanales propios. Trámites, permisos sanitarios, fitosanitarios y certificados de origen.' },
        { name: 'Almacenaje & Consolidación', desc: 'Bodegas refrigeradas y secas en puntos estratégicos. Cross-docking, picking y consolidación de carga.' },
      ],
    },
    products: {
      num: '02',
      title: ['Frutas, verduras', 'y carga general.'],
      titleEm: 'verduras',
      lede: 'Nuestro portafolio principal son productos agrícolas frescos. Cotizamos también carga general por contenedor bajo solicitud.',
      cta: 'Ver catálogo completo',
      items: [
        { name: 'Aguacate Hass', cat: 'Fruta · Mx', tag: 'A1', placeholder: 'Aguacate', img: 'https://images.unsplash.com/photo-1601039641847-7857b994d704?w=600&q=80&auto=format&fit=crop' },
        { name: 'Limón Persa', cat: 'Fruta · Mx', tag: 'A2', placeholder: 'Limón', img: 'https://images.unsplash.com/photo-1582287014914-1db836256bd9?w=600&q=80&auto=format&fit=crop' },
        { name: 'Mango Ataulfo', cat: 'Fruta · Mx', tag: 'A3', placeholder: 'Mango', img: 'https://images.unsplash.com/photo-1605027990121-cbae9e0642db?w=600&q=80&auto=format&fit=crop' },
        { name: 'Berries', cat: 'Fruta · Mx', tag: 'A4', placeholder: 'Berries', img: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&q=80&auto=format&fit=crop' },
        { name: 'Tomate Saladette', cat: 'Verdura · Mx', tag: 'B1', placeholder: 'Tomate', img: 'https://images.unsplash.com/photo-1546470427-227df1e3a13b?w=600&q=80&auto=format&fit=crop' },
        { name: 'Pimiento', cat: 'Verdura · Mx', tag: 'B2', placeholder: 'Pimiento', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80&auto=format&fit=crop' },
        { name: 'Cebolla', cat: 'Verdura · Mx', tag: 'B3', placeholder: 'Cebolla', img: 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbf?w=600&q=80&auto=format&fit=crop' },
        { name: 'Espárrago', cat: 'Verdura · Pe', tag: 'B4', placeholder: 'Espárrago', img: 'https://images.unsplash.com/photo-1515471209610-dae1c92d8777?w=600&q=80&auto=format&fit=crop' },
      ],
    },
    presence: {
      num: '03',
      title: ['Presencia en', '16 países.'],
      titleEm: '16 países',
      lede: 'Trabajamos con socios estratégicos, despachadores aduanales y almacenes en cada destino. Nuestra red opera 24/7 en cinco continentes.',
      countries: [
        { name: 'México', code: 'MX' }, { name: 'Estados Unidos', code: 'US' },
        { name: 'Canadá', code: 'CA' }, { name: 'España', code: 'ES' },
        { name: 'Italia', code: 'IT' }, { name: 'Inglaterra', code: 'GB' },
        { name: 'Francia', code: 'FR' }, { name: 'Holanda', code: 'NL' },
        { name: 'Marruecos', code: 'MA' }, { name: 'Rusia', code: 'RU' },
        { name: 'Dubai (EAU)', code: 'AE' }, { name: 'Colombia', code: 'CO' },
        { name: 'Perú', code: 'PE' }, { name: 'República Dominicana', code: 'DO' },
        { name: 'Chile', code: 'CL' }, { name: 'Argentina', code: 'AR' },
      ],
    },
    diff: {
      num: '04',
      title: ['Lo que nos', 'distingue.'],
      titleEm: 'distingue',
      items: [
        { n: '01', t: 'Seguridad', d: 'Cadena de custodia trazable extremo a extremo. Seguros de carga internacionales y protocolos de inspección en origen y destino.' },
        { n: '02', t: 'Tiempo de respuesta', d: 'Cotización formal en menos de 24 horas. Booking, documentación y despacho coordinados por un solo punto de contacto.' },
        { n: '03', t: 'Cumplimiento', d: '99.4% de operaciones entregadas en ventana acordada. Penalización propia ante retrasos imputables a Euromex.' },
      ],
    },
    cases: {
      num: '05',
      title: ['Lo que dicen', 'nuestros clientes.'],
      titleEm: 'clientes',
      items: [
        { q: 'Llevamos cuatro años importando aguacate con Euromex. Cero incidentes, cero retrasos. Es el estándar contra el que medimos a otros.', n: 'María Calleja', r: 'Directora de compras · Cadena Mediterránea' },
        { q: 'Coordinaron una operación urgente a Dubai en 11 días, con permisos fitosanitarios incluidos. Ningún otro operador nos lo había logrado.', n: 'Andrés Beltrán', r: 'CEO · Frutícola del Pacífico' },
        { q: 'Su equipo entiende el negocio agrícola. Eso se nota cuando hay imprevistos y se necesitan decisiones en minutos, no en días.', n: 'Lucía Penagos', r: 'Gerente · Distribuidora Andina' },
      ],
    },
    cta: {
      title: ['Listos para mover', 'tu próximo contenedor.'],
      titleEm: 'contenedor',
      desc: 'Cotización formal en menos de 24 horas, sin compromiso.',
      btn: 'Solicitar cotización',
    },
    foot: {
      tag: 'Soluciones integrales de exportación. Mercancía por contenedor a 16 países desde México.',
      cols: [
        { h: 'Servicios', items: ['Importación', 'Exportación', 'Aduanas', 'Almacenaje', 'Consolidación'] },
        { h: 'Productos', items: ['Frutas frescas', 'Verduras', 'Carga general', 'Bajo cotización'] },
        { h: 'Empresa', items: ['Sobre Euromex', 'Casos de éxito', 'Certificaciones', 'Contacto'] },
        { h: 'Contacto', items: ['contacto@euromex.mx', '+52 (33) 0000 0000', 'Guadalajara, Jal.'] },
      ],
      legal: '© 2026 GRUPO EUROMEX · TODOS LOS DERECHOS RESERVADOS',
      iso: 'ISO 9001:2015 · OEA · IATA',
    },
    quote: {
      title: ['Solicita tu', 'cotización.'],
      titleEm: 'cotización',
      lede: 'Respondemos en menos de 24 horas con una propuesta formal: ruta, tiempos, costos y documentación.',
      stepsTitle: 'Tu solicitud',
      steps: ['Tipo de operación', 'Producto y volumen', 'Ruta y tiempos', 'Datos de contacto'],
      f: {
        operation: 'Tipo de operación',
        operationOptions: ['Exportación', 'Importación', 'Logística completa'],
        modal: 'Modalidad de transporte',
        modalOptions: ['Marítimo', 'Aéreo', 'Terrestre', 'Multimodal'],
        product: 'Producto principal',
        productPh: 'Ej. Aguacate Hass · Tomate · Carga general',
        category: 'Categoría',
        categoryOptions: ['Fruta fresca', 'Verdura fresca', 'Carga general', 'Otro'],
        volume: 'Volumen',
        volumePh: 'Ej. 2 contenedores 40 HC',
        frequency: 'Frecuencia',
        frequencyOptions: ['Una vez', 'Mensual', 'Semanal', 'Continua'],
        origin: 'Origen',
        originPh: 'Ciudad / puerto de origen',
        destination: 'Destino',
        destinationPh: 'Ciudad / puerto de destino',
        target: 'Fecha objetivo',
        company: 'Empresa',
        companyPh: 'Razón social',
        name: 'Nombre',
        namePh: 'Tu nombre',
        email: 'Correo',
        emailPh: 'tu@empresa.com',
        phone: 'Teléfono',
        phonePh: '+52 ...',
        notes: 'Notas adicionales',
        notesPh: 'Especificaciones, certificaciones requeridas, condiciones especiales...',
        submit: 'Enviar solicitud',
        note: 'RESPONDEMOS EN < 24H · OPERACIÓN CONFIDENCIAL',
      },
      success: {
        t: 'Solicitud recibida.',
        d: 'Un asesor de Euromex te contactará en menos de 24 horas con una cotización formal.',
        btn: 'Volver al inicio',
      },
    },
    pp: {
      eyebrow: 'CATÁLOGO',
      title: ['Productos', 'disponibles.'],
      titleEm: 'disponibles',
      lede: 'Nuestro portafolio agrícola y de carga general. Todos disponibles para venta por contenedor con cotización a la medida.',
      filters: ['Todos', 'Fruta', 'Verdura', 'Carga general', 'Bajo solicitud'],
      headers: ['', 'Producto', 'Origen', 'Empaque', 'Disponibilidad', ''],
      cta: 'Cotizar',
    },
  },
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      products: 'Products',
      about: 'About',
      cases: 'Cases',
      quote: 'Get a quote',
    },
    hero: {
      eyebrow: 'International trade · Import and export',
      kicker: 'Foreign-trade operators',
      lineA: 'From the field',
      lineB: 'to the port',
      lineC: 'to the world.',
      titleEm: 'to the world',
      lede: 'We move containers of produce and general cargo to 16 countries through our own network of customs brokers, refrigerated warehouses and maritime agents. One signature, one accountable party.',
      ctaPrimary: 'Request a quote',
      ctaSecondary: 'View live operations',
      stats: [
        { n: '16+', l: 'Active markets' },
        { n: '20', l: 'Years operating' },
        { n: '99.4%', l: 'On-time delivery' },
      ],
      live: [
        { code: 'MZT → ROT', cargo: 'Hass Avocado', status: 'AT SEA' },
        { code: 'GDL → DXB', cargo: 'Persian Lime', status: 'CUSTOMS' },
        { code: 'LIM → BCN', cargo: 'Asparagus', status: 'LOADED' },
      ],
    },
    parallax: {
      lineA: 'Right now,',
      lineB: 'we are moving this.',
    },
    ticker: ['SEA FREIGHT', 'AIR FREIGHT', 'GROUND', 'CUSTOMS', 'WAREHOUSING', 'CONSOLIDATION', 'CARGO INSURANCE', '24/7 TRACKING', 'FCL', 'LCL'],
    services: {
      num: '01',
      title: ['Global logistics', 'services.'],
      titleEm: 'logistics',
      lede: 'We handle every leg of the journey, from origin to destination. One point of contact for your full export and import flow.',
      items: [
        { name: 'Import', desc: 'End-to-end FCL imports including tariff advisory, customs clearance and final-mile delivery.' },
        { name: 'Export', desc: 'Coordinated exports of produce and general cargo to leading markets in Europe, the Americas and Asia.' },
        { name: 'Logistics & Customs', desc: 'In-house customs broker network. Permits, sanitary and phytosanitary certificates, certificates of origin.' },
        { name: 'Warehousing & Consolidation', desc: 'Refrigerated and dry warehouses at strategic hubs. Cross-docking, picking and freight consolidation.' },
      ],
    },
    products: {
      num: '02',
      title: ['Fresh produce', 'and general cargo.'],
      titleEm: 'produce',
      lede: 'Our core portfolio is fresh agricultural products. We also quote general cargo by container on request.',
      cta: 'View full catalog',
      items: [
        { name: 'Hass Avocado', cat: 'Fruit · Mx', tag: 'A1', placeholder: 'Avocado', img: 'https://images.unsplash.com/photo-1601039641847-7857b994d704?w=600&q=80&auto=format&fit=crop' },
        { name: 'Persian Lime', cat: 'Fruit · Mx', tag: 'A2', placeholder: 'Lime', img: 'https://images.unsplash.com/photo-1582287014914-1db836256bd9?w=600&q=80&auto=format&fit=crop' },
        { name: 'Ataulfo Mango', cat: 'Fruit · Mx', tag: 'A3', placeholder: 'Mango', img: 'https://images.unsplash.com/photo-1605027990121-cbae9e0642db?w=600&q=80&auto=format&fit=crop' },
        { name: 'Berries', cat: 'Fruit · Mx', tag: 'A4', placeholder: 'Berries', img: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=600&q=80&auto=format&fit=crop' },
        { name: 'Roma Tomato', cat: 'Veg · Mx', tag: 'B1', placeholder: 'Tomato', img: 'https://images.unsplash.com/photo-1546470427-227df1e3a13b?w=600&q=80&auto=format&fit=crop' },
        { name: 'Bell Pepper', cat: 'Veg · Mx', tag: 'B2', placeholder: 'Pepper', img: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80&auto=format&fit=crop' },
        { name: 'Onion', cat: 'Veg · Mx', tag: 'B3', placeholder: 'Onion', img: 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbf?w=600&q=80&auto=format&fit=crop' },
        { name: 'Asparagus', cat: 'Veg · Pe', tag: 'B4', placeholder: 'Asparagus', img: 'https://images.unsplash.com/photo-1515471209610-dae1c92d8777?w=600&q=80&auto=format&fit=crop' },
      ],
    },
    presence: {
      num: '03',
      title: ['Active in', '16 countries.'],
      titleEm: '16 countries',
      lede: 'We work with strategic partners, customs brokers and warehouses at every destination. Our network operates 24/7 across five continents.',
      countries: [
        { name: 'Mexico', code: 'MX' }, { name: 'United States', code: 'US' },
        { name: 'Canada', code: 'CA' }, { name: 'Spain', code: 'ES' },
        { name: 'Italy', code: 'IT' }, { name: 'United Kingdom', code: 'GB' },
        { name: 'France', code: 'FR' }, { name: 'Netherlands', code: 'NL' },
        { name: 'Morocco', code: 'MA' }, { name: 'Russia', code: 'RU' },
        { name: 'Dubai (UAE)', code: 'AE' }, { name: 'Colombia', code: 'CO' },
        { name: 'Peru', code: 'PE' }, { name: 'Dominican Republic', code: 'DO' },
        { name: 'Chile', code: 'CL' }, { name: 'Argentina', code: 'AR' },
      ],
    },
    diff: {
      num: '04',
      title: ['What sets us', 'apart.'],
      titleEm: 'apart',
      items: [
        { n: '01', t: 'Security', d: 'Fully traceable chain of custody. International cargo insurance and inspection protocols at both origin and destination.' },
        { n: '02', t: 'Response time', d: 'Formal quote in under 24 hours. Booking, documentation and clearance coordinated through a single point of contact.' },
        { n: '03', t: 'Reliability', d: '99.4% of operations delivered within agreed window. Built-in penalty for any Euromex-attributable delay.' },
      ],
    },
    cases: {
      num: '05',
      title: ['What our', 'clients say.'],
      titleEm: 'clients',
      items: [
        { q: 'Four years importing avocados with Euromex. Zero incidents, zero delays. They are the benchmark we measure others against.', n: 'María Calleja', r: 'Head of sourcing · Mediterranean Retail' },
        { q: 'They pulled off an emergency shipment to Dubai in 11 days, including phyto permits. No other operator had managed it.', n: 'Andrés Beltrán', r: 'CEO · Pacífico Produce' },
        { q: 'Their team understands the agriculture business. It shows when something unexpected happens and you need decisions in minutes.', n: 'Lucía Penagos', r: 'Manager · Andina Distribution' },
      ],
    },
    cta: {
      title: ['Ready to move', 'your next container.'],
      titleEm: 'container',
      desc: 'Formal quote in under 24 hours, no commitment.',
      btn: 'Request a quote',
    },
    foot: {
      tag: 'Integrated export solutions. Full-container freight to 16 countries from Mexico.',
      cols: [
        { h: 'Services', items: ['Import', 'Export', 'Customs', 'Warehousing', 'Consolidation'] },
        { h: 'Products', items: ['Fresh fruit', 'Vegetables', 'General cargo', 'On request'] },
        { h: 'Company', items: ['About Euromex', 'Cases', 'Certifications', 'Contact'] },
        { h: 'Contact', items: ['contact@euromex.mx', '+52 (33) 0000 0000', 'Guadalajara, Mx'] },
      ],
      legal: '© 2026 GRUPO EUROMEX · ALL RIGHTS RESERVED',
      iso: 'ISO 9001:2015 · OEA · IATA',
    },
    quote: {
      title: ['Request your', 'quote.'],
      titleEm: 'quote',
      lede: 'We respond in under 24 hours with a formal proposal: routing, timing, costs and documentation.',
      stepsTitle: 'Your request',
      steps: ['Operation type', 'Product & volume', 'Route & timing', 'Contact details'],
      f: {
        operation: 'Operation type',
        operationOptions: ['Export', 'Import', 'Full logistics'],
        modal: 'Transport mode',
        modalOptions: ['Sea', 'Air', 'Ground', 'Multimodal'],
        product: 'Main product',
        productPh: 'e.g. Hass Avocado · Tomato · General cargo',
        category: 'Category',
        categoryOptions: ['Fresh fruit', 'Fresh vegetable', 'General cargo', 'Other'],
        volume: 'Volume',
        volumePh: 'e.g. 2× 40 HC containers',
        frequency: 'Frequency',
        frequencyOptions: ['One-off', 'Monthly', 'Weekly', 'Ongoing'],
        origin: 'Origin',
        originPh: 'City / port of origin',
        destination: 'Destination',
        destinationPh: 'City / port of destination',
        target: 'Target date',
        company: 'Company',
        companyPh: 'Legal name',
        name: 'Name',
        namePh: 'Your name',
        email: 'Email',
        emailPh: 'you@company.com',
        phone: 'Phone',
        phonePh: '+1 ...',
        notes: 'Additional notes',
        notesPh: 'Specifications, required certifications, special conditions...',
        submit: 'Submit request',
        note: 'WE REPLY IN < 24H · CONFIDENTIAL',
      },
      success: {
        t: 'Request received.',
        d: 'A Euromex advisor will contact you within 24 hours with a formal quote.',
        btn: 'Back to home',
      },
    },
    pp: {
      eyebrow: 'CATALOG',
      title: ['Available', 'products.'],
      titleEm: 'products',
      lede: 'Our agricultural and general-cargo portfolio. All available for full-container sale with custom quotes.',
      filters: ['All', 'Fruit', 'Vegetable', 'General cargo', 'On request'],
      headers: ['', 'Product', 'Origin', 'Packaging', 'Availability', ''],
      cta: 'Quote',
    },
  },
};

const PRODUCT_CATALOG = [
  { tag: 'A1', name: 'Aguacate Hass', nameEn: 'Hass Avocado', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Caja 4kg', avail: 'Todo el año' },
  { tag: 'A2', name: 'Limón Persa', nameEn: 'Persian Lime', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Caja 18kg', avail: 'Todo el año' },
  { tag: 'A3', name: 'Mango Ataulfo', nameEn: 'Ataulfo Mango', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Caja 4kg', avail: 'Mar — Sep' },
  { tag: 'A4', name: 'Berries (mix)', nameEn: 'Berries (mix)', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Clamshell 170g', avail: 'Oct — May' },
  { tag: 'A5', name: 'Piña', nameEn: 'Pineapple', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Caja 12kg', avail: 'Todo el año' },
  { tag: 'A6', name: 'Papaya Maradol', nameEn: 'Maradol Papaya', cat: 'Fruta', catEn: 'Fruit', origin: 'México', pkg: 'Caja 18kg', avail: 'Todo el año' },
  { tag: 'B1', name: 'Tomate Saladette', nameEn: 'Roma Tomato', cat: 'Verdura', catEn: 'Vegetable', origin: 'México', pkg: 'Caja 13kg', avail: 'Todo el año' },
  { tag: 'B2', name: 'Pimiento Morrón', nameEn: 'Bell Pepper', cat: 'Verdura', catEn: 'Vegetable', origin: 'México', pkg: 'Caja 5kg', avail: 'Todo el año' },
  { tag: 'B3', name: 'Cebolla Blanca', nameEn: 'White Onion', cat: 'Verdura', catEn: 'Vegetable', origin: 'México', pkg: 'Saco 22kg', avail: 'Todo el año' },
  { tag: 'B4', name: 'Espárrago Verde', nameEn: 'Green Asparagus', cat: 'Verdura', catEn: 'Vegetable', origin: 'Perú', pkg: 'Caja 5kg', avail: 'Sep — Mar' },
  { tag: 'B5', name: 'Pepino', nameEn: 'Cucumber', cat: 'Verdura', catEn: 'Vegetable', origin: 'México', pkg: 'Caja 13kg', avail: 'Todo el año' },
  { tag: 'B6', name: 'Calabaza Italiana', nameEn: 'Zucchini', cat: 'Verdura', catEn: 'Vegetable', origin: 'México', pkg: 'Caja 9kg', avail: 'Todo el año' },
  { tag: 'C1', name: 'Carga general', nameEn: 'General cargo', cat: 'Carga general', catEn: 'General cargo', origin: 'Diversos', pkg: 'A consultar', avail: 'Bajo solicitud' },
  { tag: 'C2', name: 'Productos secos', nameEn: 'Dry goods', cat: 'Carga general', catEn: 'General cargo', origin: 'Diversos', pkg: 'A consultar', avail: 'Bajo solicitud' },
];

window.COPY = COPY;
window.PRODUCT_CATALOG = PRODUCT_CATALOG;
